// Demo Application Module (DAM) — Fictional sample data for all institution dashboards.
// All names, IDs, NIDs and case references are entirely fictional. No real citizen data.
import type { Suspect, IntelligenceEvent, Alert, CameraNode, DashboardStats, Case, SiemEvent } from '@/types'

export const DAM_STATS: DashboardStats = {
  total_suspects: 12,
  wanted_count: 4,
  in_custody_count: 3,
  active_warrants: 7,
  alerts_today: 5,
  critical_alerts: 2,
  events_today: 23,
  camera_nodes_online: 8,
  camera_nodes_total: 10,
}

export const DAM_SUSPECTS: Suspect[] = [
  {
    id: 'dam-s1',
    ims_reference: 'RWA-IMS-2024-00001',
    full_name: 'Alexis Mugisha',
    alias: 'The Shadow',
    status: 'WANTED',
    threat_level: 5,
    nationality: 'RWA',
    date_of_birth: '1978-03-14',
    physical_description: 'Male, 178 cm, scar on left cheek, eagle tattoo on right forearm',
    known_associates: ['Eric Ndayambaje', 'Vital Bizimungu'],
    institution_classification: 'RNP',
    clearance_required: 'TOP_SECRET',
    created_at: '2024-03-10T08:00:00Z',
    updated_at: '2026-06-28T11:30:00Z',
  },
  {
    id: 'dam-s2',
    ims_reference: 'RWA-IMS-2024-00002',
    full_name: 'Christine Uwimana',
    alias: 'Mama Finance',
    status: 'IN_CUSTODY',
    threat_level: 3,
    nationality: 'RWA',
    date_of_birth: '1985-07-22',
    physical_description: 'Female, 162 cm, brown eyes',
    institution_classification: 'RIB',
    clearance_required: 'CONFIDENTIAL',
    created_at: '2024-05-17T09:15:00Z',
    updated_at: '2026-06-01T14:00:00Z',
  },
  {
    id: 'dam-s3',
    ims_reference: 'RWA-IMS-2023-00001',
    full_name: 'Pierre Nsengiyumva',
    status: 'CONVICTED',
    threat_level: 4,
    nationality: 'RWA',
    date_of_birth: '1970-04-05',
    physical_description: 'Male, 172 cm, shaved head, missing tip of right index finger',
    institution_classification: 'RCS',
    clearance_required: 'SECRET',
    created_at: '2023-11-02T07:30:00Z',
    updated_at: '2025-08-15T10:00:00Z',
  },
  {
    id: 'dam-s4',
    ims_reference: 'RWA-IMS-2025-00001',
    full_name: 'Dieudonne Kabera',
    alias: 'D-Code',
    status: 'ACTIVE',
    threat_level: 3,
    nationality: 'RWA',
    date_of_birth: '1992-11-30',
    physical_description: 'Male, 175 cm, glasses',
    institution_classification: 'RIB',
    clearance_required: 'SECRET',
    created_at: '2025-01-14T11:00:00Z',
    updated_at: '2026-06-20T09:45:00Z',
  },
  {
    id: 'dam-s5',
    ims_reference: 'RWA-IMS-2024-00003',
    full_name: 'Goreth Mukamana',
    status: 'WANTED',
    threat_level: 4,
    nationality: 'RWA',
    date_of_birth: '1988-09-15',
    physical_description: 'Female, 165 cm, braided hair, gold tooth (upper right)',
    institution_classification: 'RNP',
    clearance_required: 'SECRET',
    created_at: '2024-08-22T14:20:00Z',
    updated_at: '2026-06-27T16:00:00Z',
  },
  {
    id: 'dam-s6',
    ims_reference: 'RWA-IMS-2025-00002',
    full_name: 'Jean Niyongabo',
    alias: 'Black Eagle',
    status: 'INTERPOL_FLAGGED',
    threat_level: 5,
    nationality: 'DRC',
    date_of_birth: '1975-12-01',
    physical_description: 'Male, 183 cm, tribal markings on neck',
    institution_classification: 'NISS',
    clearance_required: 'TOP_SECRET',
    created_at: '2025-03-07T06:00:00Z',
    updated_at: '2026-06-22T08:00:00Z',
  },
  {
    id: 'dam-s7',
    ims_reference: 'RWA-IMS-2026-00001',
    full_name: 'Fidele Hakizimana',
    status: 'ARRESTED',
    threat_level: 3,
    nationality: 'RWA',
    date_of_birth: '1980-06-18',
    physical_description: 'Male, 170 cm, stocky build',
    institution_classification: 'RIB',
    clearance_required: 'CONFIDENTIAL',
    created_at: '2026-04-10T10:30:00Z',
    updated_at: '2026-06-15T13:00:00Z',
  },
  {
    id: 'dam-s8',
    ims_reference: 'RWA-IMS-2024-00004',
    full_name: 'Solange Uwera',
    status: 'RELEASED',
    threat_level: 2,
    nationality: 'RWA',
    date_of_birth: '1995-02-08',
    institution_classification: 'RCS',
    clearance_required: 'UNCLASSIFIED',
    created_at: '2024-10-01T08:00:00Z',
    updated_at: '2026-03-12T09:00:00Z',
  },
  {
    id: 'dam-s9',
    ims_reference: 'RWA-IMS-2025-00003',
    full_name: 'Vital Bizimungu',
    alias: 'Vee-B',
    status: 'ACTIVE',
    threat_level: 3,
    nationality: 'RWA',
    date_of_birth: '1983-07-11',
    physical_description: 'Male, 169 cm, thin beard, limp in left leg',
    institution_classification: 'RDF',
    clearance_required: 'SECRET',
    created_at: '2025-06-05T13:00:00Z',
    updated_at: '2026-06-28T07:00:00Z',
  },
  {
    id: 'dam-s10',
    ims_reference: 'RWA-IMS-2025-00004',
    full_name: 'Eric Ndayambaje',
    alias: 'The Mule',
    status: 'WANTED',
    threat_level: 4,
    nationality: 'RWA',
    date_of_birth: '1987-04-23',
    physical_description: 'Male, 177 cm, cross scar on left hand',
    known_associates: ['Alexis Mugisha'],
    institution_classification: 'RNP',
    clearance_required: 'SECRET',
    created_at: '2025-08-14T09:00:00Z',
    updated_at: '2026-06-29T06:00:00Z',
  },
  {
    id: 'dam-s11',
    ims_reference: 'RWA-IMS-2023-00002',
    full_name: 'Theodore Karangwa',
    status: 'CONVICTED',
    threat_level: 4,
    nationality: 'RWA',
    date_of_birth: '1969-01-27',
    institution_classification: 'RCS',
    clearance_required: 'CONFIDENTIAL',
    created_at: '2023-05-18T11:00:00Z',
    updated_at: '2025-11-20T12:00:00Z',
  },
  {
    id: 'dam-s12',
    ims_reference: 'RWA-IMS-2026-00002',
    full_name: 'Cecile Iradukunda',
    alias: 'Ice Queen',
    status: 'ACTIVE',
    threat_level: 3,
    nationality: 'RWA',
    date_of_birth: '1990-10-14',
    physical_description: 'Female, 160 cm, short natural hair, silver bracelet on right wrist',
    institution_classification: 'NISS',
    clearance_required: 'TOP_SECRET',
    created_at: '2026-02-18T07:30:00Z',
    updated_at: '2026-06-29T05:00:00Z',
  },
]

export const DAM_EVENTS: IntelligenceEvent[] = [
  {
    id: 'dam-ev1',
    source_tag: 'CCTV_NODE',
    suspect_id: 'dam-s9',
    suspect_name: 'Vital Bizimungu',
    ims_reference: 'RWA-IMS-2025-00003',
    camera_node_id: 'GTN-BORDER-01',
    confidence_score: 0.941,
    criminal_record_found: true,
    alert_generated: true,
    location_lat: -1.7018,
    location_lng: 29.7350,
    location_description: 'Gatuna Border Post — Entry Lane',
    created_at: '2026-06-29T13:47:00Z',
  },
  {
    id: 'dam-ev2',
    source_tag: 'NID_SCAN',
    suspect_name: 'Alexis Mugisha',
    suspect_id: 'dam-s1',
    ims_reference: 'RWA-IMS-2024-00001',
    reporting_officer_id: 'off-rnp-pat-006',
    confidence_score: 1.0,
    criminal_record_found: true,
    alert_generated: true,
    location_lat: -1.9441,
    location_lng: 30.0619,
    location_description: 'Nyabugogo Checkpoint, Kigali',
    created_at: '2026-06-29T11:22:00Z',
  },
  {
    id: 'dam-ev3',
    source_tag: 'FACE_SCAN',
    suspect_name: 'Goreth Mukamana',
    suspect_id: 'dam-s5',
    ims_reference: 'RWA-IMS-2024-00003',
    reporting_officer_id: 'off-rdf-brd-001',
    confidence_score: 0.883,
    criminal_record_found: true,
    alert_generated: true,
    location_lat: -1.9706,
    location_lng: 30.1328,
    location_description: 'Kigali International Airport',
    created_at: '2026-06-29T09:55:00Z',
  },
  {
    id: 'dam-ev4',
    source_tag: 'NID_MANUAL',
    criminal_record_found: false,
    alert_generated: false,
    reporting_officer_id: 'off-rnp-det-003',
    created_at: '2026-06-29T09:10:00Z',
  },
  {
    id: 'dam-ev5',
    source_tag: 'CCTV_NODE',
    suspect_name: 'Eric Ndayambaje',
    suspect_id: 'dam-s10',
    ims_reference: 'RWA-IMS-2025-00004',
    camera_node_id: 'KGL-BUSPARK-01',
    confidence_score: 0.916,
    criminal_record_found: true,
    alert_generated: true,
    location_lat: -1.9490,
    location_lng: 30.0578,
    location_description: 'Nyabugogo Bus Terminal, Bay 12',
    created_at: '2026-06-29T08:30:00Z',
  },
  {
    id: 'dam-ev6',
    source_tag: 'OFFICER_REPORT',
    suspect_name: 'Fidele Hakizimana',
    suspect_id: 'dam-s7',
    ims_reference: 'RWA-IMS-2026-00001',
    reporting_officer_id: 'off-rib-inv-001',
    criminal_record_found: true,
    alert_generated: true,
    notes: 'Suspect sighted near Remera market, appeared to recognize patrol officers and moved away quickly.',
    created_at: '2026-06-28T18:14:00Z',
  },
  {
    id: 'dam-ev7',
    source_tag: 'INTERPOL_FEED',
    suspect_name: 'Jean Niyongabo',
    suspect_id: 'dam-s6',
    ims_reference: 'RWA-IMS-2025-00002',
    criminal_record_found: true,
    alert_generated: true,
    notes: 'Interpol Red Notice ingested — file DRC-2025-RN-00892. Cross-border armed criminal.',
    created_at: '2026-06-28T16:00:00Z',
  },
  {
    id: 'dam-ev8',
    source_tag: 'FACE_SCAN',
    suspect_name: 'Cecile Iradukunda',
    suspect_id: 'dam-s12',
    ims_reference: 'RWA-IMS-2026-00002',
    reporting_officer_id: 'off-niss-off-003',
    confidence_score: 0.754,
    criminal_record_found: true,
    alert_generated: false,
    notes: 'Probable match (confidence 75.4%) — manual verification requested.',
    created_at: '2026-06-28T12:30:00Z',
  },
  {
    id: 'dam-ev9',
    source_tag: 'NID_SCAN',
    criminal_record_found: false,
    alert_generated: false,
    reporting_officer_id: 'off-rnp-pat-006',
    notes: 'Clean citizen. NID checked, no record found. Data discarded per privacy policy.',
    created_at: '2026-06-28T10:00:00Z',
  },
  {
    id: 'dam-ev10',
    source_tag: 'CCTV_NODE',
    suspect_name: 'Jean Niyongabo',
    suspect_id: 'dam-s6',
    ims_reference: 'RWA-IMS-2025-00002',
    camera_node_id: 'KGL-AIRPORT-01',
    confidence_score: 0.872,
    criminal_record_found: true,
    alert_generated: true,
    location_description: 'Kigali International Airport — Arrivals Hall',
    created_at: '2026-06-28T07:22:00Z',
  },
  {
    id: 'dam-ev11',
    source_tag: 'SYSTEM_ALERT',
    criminal_record_found: false,
    alert_generated: true,
    notes: 'SIEM rule BULK_ENUMERATION triggered — 62 suspect queries in 9 minutes from session SESS-7A4F2.',
    created_at: '2026-06-27T22:45:00Z',
  },
  {
    id: 'dam-ev12',
    source_tag: 'NID_SCAN',
    suspect_name: 'Christine Uwimana',
    suspect_id: 'dam-s2',
    ims_reference: 'RWA-IMS-2024-00002',
    reporting_officer_id: 'off-rcs-sup-001',
    confidence_score: 1.0,
    criminal_record_found: true,
    alert_generated: false,
    location_description: 'Mageragere Correctional Facility — Intake',
    created_at: '2026-06-27T09:00:00Z',
  },
  {
    id: 'dam-ev13',
    source_tag: 'PARTNER_QUERY',
    suspect_name: 'Jean Niyongabo',
    suspect_id: 'dam-s6',
    criminal_record_found: true,
    alert_generated: false,
    notes: 'Uganda Police Force face query — bilateral query under Rwanda-Uganda MOU. Confirmed match.',
    created_at: '2026-06-26T14:00:00Z',
  },
  {
    id: 'dam-ev14',
    source_tag: 'CCTV_NODE',
    suspect_name: 'Alexis Mugisha',
    suspect_id: 'dam-s1',
    ims_reference: 'RWA-IMS-2024-00001',
    camera_node_id: 'MSZ-JUNCTION-01',
    confidence_score: 0.791,
    criminal_record_found: true,
    alert_generated: true,
    location_description: 'Musanze Junction Camera — Northern Road',
    created_at: '2026-06-25T20:18:00Z',
  },
]

export const DAM_ALERTS: Alert[] = [
  {
    id: 'dam-al1',
    severity: 'CRITICAL',
    title: 'WANTED Suspect Detected — Gatuna Border',
    message: 'Vital Bizimungu (RWA-IMS-2025-00003) detected at Gatuna Border Post, GTN-BORDER-01. Confidence 94.1%. Threat Level 3.',
    source_tag: 'CCTV_NODE',
    suspect_id: 'dam-s9',
    suspect_name: 'Vital Bizimungu',
    is_read: false,
    requires_action: true,
    created_at: '2026-06-29T13:47:00Z',
  },
  {
    id: 'dam-al2',
    severity: 'CRITICAL',
    title: 'HIGH-THREAT Suspect NID Check — Kigali',
    message: 'Alexis Mugisha (RWA-IMS-2024-00001, Threat 5) confirmed via NID scan at Nyabugogo Checkpoint. Officer GPS captured.',
    source_tag: 'NID_SCAN',
    suspect_id: 'dam-s1',
    suspect_name: 'Alexis Mugisha',
    is_read: false,
    requires_action: true,
    created_at: '2026-06-29T11:22:00Z',
  },
  {
    id: 'dam-al3',
    severity: 'HIGH',
    title: 'Face Match — Airport Arrivals (WANTED)',
    message: 'Goreth Mukamana (RWA-IMS-2024-00003) matched at Kigali Airport, confidence 88.3%. RNP notified.',
    source_tag: 'FACE_SCAN',
    suspect_id: 'dam-s5',
    suspect_name: 'Goreth Mukamana',
    is_read: false,
    requires_action: true,
    created_at: '2026-06-29T09:55:00Z',
  },
  {
    id: 'dam-al4',
    severity: 'HIGH',
    title: 'WANTED Suspect at Bus Terminal',
    message: 'Eric Ndayambaje (RWA-IMS-2025-00004) detected at Nyabugogo Bus Terminal by KGL-BUSPARK-01. Confidence 91.6%.',
    source_tag: 'CCTV_NODE',
    suspect_id: 'dam-s10',
    suspect_name: 'Eric Ndayambaje',
    is_read: false,
    requires_action: true,
    created_at: '2026-06-29T08:30:00Z',
  },
  {
    id: 'dam-al5',
    severity: 'MEDIUM',
    title: 'Interpol Red Notice Ingested',
    message: 'Jean Niyongabo (RWA-IMS-2025-00002, INTERPOL_FLAGGED) — Red Notice DRC-2025-RN-00892 automatically ingested via I-24/7 feed.',
    source_tag: 'INTERPOL_FEED',
    suspect_id: 'dam-s6',
    suspect_name: 'Jean Niyongabo',
    is_read: true,
    requires_action: false,
    created_at: '2026-06-28T16:00:00Z',
  },
  {
    id: 'dam-al6',
    severity: 'MEDIUM',
    title: 'SIEM: Bulk Enumeration Detected',
    message: 'SIEM rule BULK_ENUMERATION triggered — 62 suspect queries in 9 minutes from session SESS-7A4F2. User temporarily rate-limited.',
    source_tag: 'SYSTEM_ALERT',
    is_read: true,
    requires_action: true,
    created_at: '2026-06-27T22:45:00Z',
  },
  {
    id: 'dam-al7',
    severity: 'LOW',
    title: 'Camera Node Offline — RBV-BORDER-02',
    message: 'No heartbeat received from RBV-BORDER-02 (Rubavu Border) for 12 minutes. RDF notified. Possible connectivity issue.',
    source_tag: 'SYSTEM_ALERT',
    is_read: true,
    requires_action: false,
    created_at: '2026-06-27T14:30:00Z',
  },
  {
    id: 'dam-al8',
    severity: 'LOW',
    title: 'Officer Report — Suspicious Activity',
    message: 'Fidele Hakizimana sighted near Remera market by RIB officer. Suspect appeared to recognise officer. Manual report submitted.',
    source_tag: 'OFFICER_REPORT',
    suspect_id: 'dam-s7',
    suspect_name: 'Fidele Hakizimana',
    is_read: true,
    requires_action: false,
    created_at: '2026-06-28T18:14:00Z',
  },
]

export const DAM_CAMERAS: CameraNode[] = [
  { id: 'dam-c1', node_identifier: 'GTN-BORDER-01', location_name: 'Gatuna Border — Entry Lane', institution: 'RDF', is_active: true,  last_heartbeat: '2026-06-29T13:48:00Z', latitude: -1.7018, longitude: 29.7350 },
  { id: 'dam-c2', node_identifier: 'GTN-BORDER-02', location_name: 'Gatuna Border — Exit Lane',  institution: 'RDF', is_active: true,  last_heartbeat: '2026-06-29T13:47:00Z', latitude: -1.7020, longitude: 29.7351 },
  { id: 'dam-c3', node_identifier: 'RBV-BORDER-01', location_name: 'Rubavu Border — Main Gate',  institution: 'RDF', is_active: true,  last_heartbeat: '2026-06-29T13:45:00Z', latitude: -1.6763, longitude: 29.3460 },
  { id: 'dam-c4', node_identifier: 'RBV-BORDER-02', location_name: 'Rubavu Border — Secondary',  institution: 'RDF', is_active: false, last_heartbeat: '2026-06-29T01:12:00Z', latitude: -1.6770, longitude: 29.3455 },
  { id: 'dam-c5', node_identifier: 'RSZ-BORDER-01', location_name: 'Rusizi Border Post',          institution: 'RDF', is_active: true,  last_heartbeat: '2026-06-29T13:40:00Z', latitude: -2.4797, longitude: 28.9078 },
  { id: 'dam-c6', node_identifier: 'NYG-BORDER-01', location_name: 'Nyagatare Border — North',   institution: 'RDF', is_active: true,  last_heartbeat: '2026-06-29T13:42:00Z', latitude: -1.2948, longitude: 30.3288 },
  { id: 'dam-c7', node_identifier: 'KGL-AIRPORT-01', location_name: 'KGL Airport — Arrivals',    institution: 'RDF', is_active: true,  last_heartbeat: '2026-06-29T13:46:00Z', latitude: -1.9706, longitude: 30.1328 },
  { id: 'dam-c8', node_identifier: 'KGL-BUSPARK-01', location_name: 'Nyabugogo Bus Terminal',     institution: 'RNP', is_active: true,  last_heartbeat: '2026-06-29T13:49:00Z', latitude: -1.9490, longitude: 30.0578 },
  { id: 'dam-c9', node_identifier: 'KGL-CBD-01',     location_name: 'Kigali CBD Junction',        institution: 'RNP', is_active: true,  last_heartbeat: '2026-06-29T13:44:00Z', latitude: -1.9500, longitude: 30.0588 },
  { id: 'dam-c10', node_identifier: 'MSZ-JUNCTION-01', location_name: 'Musanze Junction',         institution: 'RNP', is_active: false, last_heartbeat: '2026-06-28T22:10:00Z', latitude: -1.4993, longitude: 29.6327 },
]

export const DAM_CASES: Case[] = [
  { id: 'dam-case1', case_reference: 'RIB-2024-CR-00147', title: 'Kigali CBD Armed Robbery Series', status: 'UNDER_INVESTIGATION', classification: 'SECRET', lead_institution: 'RNP', created_at: '2024-03-15T08:00:00Z' },
  { id: 'dam-case2', case_reference: 'RIB-2024-FR-00031', title: 'Umurenge SACCO Financial Fraud Network', status: 'UNDER_INVESTIGATION', classification: 'CONFIDENTIAL', lead_institution: 'RIB', created_at: '2024-05-22T09:30:00Z' },
  { id: 'dam-case3', case_reference: 'RIB-2025-DT-00008', title: 'Northern Border Drug Trafficking Route', status: 'UNDER_INVESTIGATION', classification: 'SECRET', lead_institution: 'RDF', created_at: '2025-01-07T11:00:00Z' },
  { id: 'dam-case4', case_reference: 'RIB-2025-OC-00022', title: 'Cross-Border Organised Crime Cell', status: 'UNDER_INVESTIGATION', classification: 'TOP_SECRET', lead_institution: 'NISS', created_at: '2025-04-10T13:00:00Z' },
  { id: 'dam-case5', case_reference: 'RIB-2023-HO-00003', title: 'Gitarama Homicide — Pierre Nsengiyumva', status: 'CLOSED', classification: 'SECRET', lead_institution: 'RNP', created_at: '2023-11-05T07:00:00Z' },
  { id: 'dam-case6', case_reference: 'RIB-2026-CO-00011', title: 'Customs Corruption — Port of Kigali', status: 'UNDER_INVESTIGATION', classification: 'CONFIDENTIAL', lead_institution: 'RIB', created_at: '2026-04-14T10:00:00Z' },
  { id: 'dam-case7', case_reference: 'RIB-2025-TF-00005', title: 'Human Trafficking Network — Southern Region', status: 'UNDER_INVESTIGATION', classification: 'SECRET', lead_institution: 'RIB', created_at: '2025-09-03T08:30:00Z' },
  { id: 'dam-case8', case_reference: 'RIB-2024-CY-00019', title: 'Mobile Money Cybercrime Operation', status: 'PENDING_PROSECUTION', classification: 'CONFIDENTIAL', lead_institution: 'RIB', created_at: '2024-11-20T12:00:00Z' },
]

export const DAM_SIEM: SiemEvent[] = [
  { id: 'dam-se1', rule_name: 'BULK_ENUMERATION', severity: 'HIGH', description: '62 suspect queries in 9 minutes from session SESS-7A4F2 (badge RNP-DET-004)', auto_action: 'RATE_LIMIT + NISS_ALERT', reviewed: false, created_at: '2026-06-27T22:45:00Z' },
  { id: 'dam-se2', rule_name: 'CAMERA_NODE_OFFLINE', severity: 'MEDIUM', description: 'No heartbeat from RBV-BORDER-02 for >10 minutes', auto_action: 'NISS_ALERT + RDF_ALERT', reviewed: true, created_at: '2026-06-27T14:22:00Z' },
  { id: 'dam-se3', rule_name: 'OFF_HOURS_ACCESS', severity: 'MEDIUM', description: 'Badge RCS-OFF-002 authenticated at 02:47 local time', auto_action: 'LOG + NISS_ALERT', reviewed: true, created_at: '2026-06-26T00:47:00Z' },
  { id: 'dam-se4', rule_name: 'MFA_BYPASS_ATTEMPT', severity: 'HIGH', description: '4 consecutive MFA failures from badge NISS-OFF-003 — possible compromise attempt', auto_action: 'LOCK_USER + NISS_ALERT', reviewed: false, created_at: '2026-06-25T09:15:00Z' },
  { id: 'dam-se5', rule_name: 'BRUTE_FORCE', severity: 'CRITICAL', description: '7 failed logins in 14 minutes targeting badge RNP-CMD-001', auto_action: 'LOCK_USER', reviewed: true, created_at: '2026-06-24T19:33:00Z' },
  { id: 'dam-se6', rule_name: 'LOCATION_OVERACCESS', severity: 'HIGH', description: '13 location record views in 45 minutes — badge RIB-ANL-001 exceeded threshold', auto_action: 'KILL_SESSION + NISS_ALERT', reviewed: false, created_at: '2026-06-23T11:08:00Z' },
]

// Event trend — last 7 days (for line / bar charts)
export const DAM_TREND = [
  { date: 'Jun 23', events: 12, alerts: 2 },
  { date: 'Jun 24', events: 18, alerts: 4 },
  { date: 'Jun 25', events: 9,  alerts: 1 },
  { date: 'Jun 26', events: 24, alerts: 5 },
  { date: 'Jun 27', events: 31, alerts: 6 },
  { date: 'Jun 28', events: 19, alerts: 3 },
  { date: 'Jun 29', events: 23, alerts: 5 },
]

// Border crossing stats — last 7 days (for RDF dashboard)
export const DAM_BORDER_CROSSINGS = [
  { date: 'Jun 23', crossings: 847, alerts: 2 },
  { date: 'Jun 24', crossings: 912, alerts: 3 },
  { date: 'Jun 25', crossings: 1043, alerts: 4 },
  { date: 'Jun 26', crossings: 978, alerts: 2 },
  { date: 'Jun 27', crossings: 1156, alerts: 5 },
  { date: 'Jun 28', crossings: 834, alerts: 1 },
  { date: 'Jun 29', crossings: 623, alerts: 2 },
]

// Inmate intake / release — last 6 months (for RCS dashboard)
export const DAM_INTAKE_RELEASES = [
  { month: 'Jan', intake: 8, releases: 3 },
  { month: 'Feb', intake: 12, releases: 5 },
  { month: 'Mar', intake: 6, releases: 7 },
  { month: 'Apr', intake: 9, releases: 4 },
  { month: 'May', intake: 14, releases: 6 },
  { month: 'Jun', intake: 7, releases: 2 },
]

// International partners (for NISS dashboard)
export const DAM_PARTNERS = [
  { country: 'Uganda', code: 'UGA', status: 'ACTIVE', mou_expires: '2028-01-01', recent_queries: 3, flag: '🇺🇬' },
  { country: 'Kenya', code: 'KEN', status: 'ACTIVE', mou_expires: '2027-06-30', recent_queries: 1, flag: '🇰🇪' },
  { country: 'DR Congo', code: 'DRC', status: 'ACTIVE', mou_expires: '2026-12-31', recent_queries: 2, flag: '🇨🇩' },
]

// Corrections records for RCS (extended data not in global types)
export interface DamCorrectionsRecord {
  id: string
  suspect_id: string
  full_name: string
  ims_reference: string
  facility: string
  cell_block: string
  intake_date: string
  status: 'PRE_TRIAL' | 'SENTENCED'
  sentence_years?: number
  next_review: string
  threat_level: number
}

export const DAM_CORRECTIONS: DamCorrectionsRecord[] = [
  { id: 'dam-cr1', suspect_id: 'dam-s2', full_name: 'Christine Uwimana', ims_reference: 'RWA-IMS-2024-00002', facility: 'Mageragere', cell_block: 'B-3', intake_date: '2026-06-01', status: 'PRE_TRIAL', next_review: '2026-07-15', threat_level: 3 },
  { id: 'dam-cr2', suspect_id: 'dam-s3', full_name: 'Pierre Nsengiyumva', ims_reference: 'RWA-IMS-2023-00001', facility: 'Nyarugenge', cell_block: 'A-1', intake_date: '2024-01-20', status: 'SENTENCED', sentence_years: 20, next_review: '2026-08-01', threat_level: 4 },
  { id: 'dam-cr3', suspect_id: 'dam-s11', full_name: 'Theodore Karangwa', ims_reference: 'RWA-IMS-2023-00002', facility: 'Nyarugenge', cell_block: 'A-4', intake_date: '2023-06-10', status: 'SENTENCED', sentence_years: 25, next_review: '2026-09-10', threat_level: 4 },
  { id: 'dam-cr4', suspect_id: 'dam-s7', full_name: 'Fidele Hakizimana', ims_reference: 'RWA-IMS-2026-00001', facility: 'Mageragere', cell_block: 'C-7', intake_date: '2026-06-15', status: 'PRE_TRIAL', next_review: '2026-07-10', threat_level: 3 },
  { id: 'dam-cr5', suspect_id: 'dam-s8', full_name: 'Solange Uwera', ims_reference: 'RWA-IMS-2024-00004', facility: 'Nyarugenge', cell_block: 'B-8', intake_date: '2024-10-01', status: 'SENTENCED', sentence_years: 3, next_review: '2026-07-05', threat_level: 2 },
]

// Patrol — officer's own verification events (demo)
export const DAM_MY_EVENTS: IntelligenceEvent[] = [
  {
    id: 'dam-me1',
    source_tag: 'NID_SCAN',
    criminal_record_found: false,
    alert_generated: false,
    reporting_officer_id: 'self',
    notes: 'Routine patrol check — no record found.',
    created_at: '2026-06-29T11:05:00Z',
  },
  {
    id: 'dam-me2',
    source_tag: 'NID_SCAN',
    criminal_record_found: true,
    alert_generated: true,
    reporting_officer_id: 'self',
    notes: 'Record found during patrol.',
    created_at: '2026-06-29T09:32:00Z',
  },
  {
    id: 'dam-me3',
    source_tag: 'FACE_SCAN',
    criminal_record_found: false,
    alert_generated: false,
    reporting_officer_id: 'self',
    created_at: '2026-06-28T16:48:00Z',
  },
  {
    id: 'dam-me4',
    source_tag: 'OFFICER_REPORT',
    criminal_record_found: false,
    alert_generated: false,
    reporting_officer_id: 'self',
    notes: 'Suspicious activity report submitted — person acting nervously near school.',
    created_at: '2026-06-28T14:20:00Z',
  },
]
